### PR TITLE
Skeleton for Articles Activity and API integration

### PR DESCRIPTION
**Pull request by christopherhwood**

### CODE REVIEW

**Comment by fernandobuzi** [comment]
Hi @bshyong. Are you able to review this PR? I think we can then give @christopherhwood access to the repo so that he can merge himself and lead the iOS part of Kanshu.

**Comment by bshyong** [comment]
will do!

## 

Ben Shyong
Co-Founder, Meddik
meddik.com | 909-274-9664

**Comment by fernandobuzi** [comment]
Great! Thanks.

**Comment by bshyong** [comment]
screen shot 2015-04-01 at 10 35 00 am

Merging

**Pull request merged**
